name: Cloud Storage Uploader
run-name: ${{ github.actor }} is testing out google-github-actions/upload-cloud-storage@v0.10.4
on: workflow_dispatch
jobs:
  job_id:
    runs-on: node16
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '/'
        destination: 'kilocrumbs.com'

    # Example of using the output
    - id: 'uploaded-files'
      uses: 'foo/bar@main'
      env:
        files: '${{ steps.upload-folder.outputs.uploaded }}'
