name: Cloud Storage Uploader
run-name: ${{ github.actor }} is testing out google-github-actions/upload-cloud-storage@v0.10.4
on: workflow_dispatch
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        parent: false
        path: '/'
        destination: 'kilocrumbs.com'
